spring:
    application:
        name: rbac

    datasource:
        url: jdbc:mysql://localhost:3306/rbac
        username: root
        password: root

    jpa:
        show-sql: true

    output:
        ansi:
            enabled: always

server:
  port: 8081